name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Configure CMake
      run: |
        rm -rf ${{ github.workspace }}/build
        mkdir ${{ github.workspace }}/build
        cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }} -DBUILD_TESTS=ON

    - name: Build
      run: |
        cmake --build ${{ github.workspace }}/build

    - name: Run tests
      run: |
        echo ${{ github.workspace }}
        ls ${{ github.workspace }}/build 
        ctest --test-dir ${{ github.workspace }}/build --output-on-failure
      working-directory: ${{ github.workspace }}/build
      
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: executable
        path: ${{ github.workspace }}/build/ZooApp 
