name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: cmake --build ./build --config Release --target all -- -j 4
      working-directory: ./build

    - name: Run tests
      run: ctest --test-dir ./build --output-on-failure
      working-directory: ./build
