name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: actions/setup-cmake@v3
      with:
        cmake-version: '3.16.x' # Укажите версию CMake, которую вы хотите использовать

    - name: Clean build directory
      run: |
        rm -rf ${{ github.workspace }}/build
        mkdir ${{ github.workspace }}/build

    - name: Configure CMake
      working-directory: ${{ github.workspace }}/build
      run: cmake ${{ github.workspace }} -DCMAKE_BUILD_TYPE=Release

    - name: Build
      working-directory: ${{ github.workspace }}/build
      run: cmake --build . --config Release
