name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Checkout submodules
      run: git submodule update --init --recursive
      
    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }} -DBUILD_TESTS=ON
        
    - name: Build
      run: |
        cmake --build ${{ github.workspace }}/build
        
    - name: Run tests
      run: |
        echo ${{ github.workspace }}
        ls ${{ github.workspace }}/build 
        chmod +x ${{ github.workspace }}/build/ProtoZoo # Добавляем разрешение на выполнение
        ${{ github.workspace }}/build/ProtoZoo # Запускаем ProtoZoo
      working-directory: ${{ github.workspace }}

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: executable
        path: ${{ github.workspace }}/build/ZooApp
